apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.3'
    defaultConfig {
        applicationId "ru.proghouse.robocam"
        minSdkVersion 9
        targetSdkVersion 25
        versionCode 19
        versionName '1.2'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        withoutRenderScript {
        }
        withRenderScript {
            versionCode 20
            renderscriptTargetApi 11
            renderscriptSupportModeEnabled true
        }
    }
    sourceSets {
        withRenderScript.renderscript.srcDirs = ['src/main/rs2']
        withRenderScript.java.srcDirs = ['src/main/java', 'src/main/rs2']
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'org.webbitserver:webbit:0.4.15'
    compile 'com.google.android.gms:play-services-ads:9.2.0'
    compile 'com.android.support:appcompat-v7:25.0.1'
}
